# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java/Kotlin project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Build and publish affected projects

on:
  workflow_run:
    workflows: ['Test all projects']
    branches: ['template-minecraft']
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This ensures all commits are fetched

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build affected projects with Gradle
        run: ./gradlew buildAffected

      - name: Publish affected artifacts to Github Packages
        run: ./gradlew publishAffected
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}